<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/jquery.placeholder.js', 'text/javascript')
            ->prependFile($this->basePath() . '/js/jquery.form.min.js')
            ->prependFile($this->basePath() . '/js/jquery.validate/jquery.validate.min.js')
            ->prependFile($this->basePath() . '/js/jquery-1.8.3.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
    	
    	<div id="wrapper">
    	
    		<div class="maincontent">
    			<div class="container" style="width: 960px !important;">
	    			<div class="row">
	    				<div class="col-xs-6">
			    			<h1 class="site-title"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></h1>
			    			<span class="site-logo"></span>
	    				</div>
	    				<div class="col-xs-5 col-md-offset-1">
	    					
				            <?php echo $this->content; ?>
	    					
	    				</div>
	    			</div>
    			</div>
    		</div><!-- .maincontent -->
			<footer class="mainfooter">
				<small>&copy; Cusque&ntilde;a</small>
			</footer>
			
			
		</div><!-- #wrapper -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
