<!--<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Welcome to %sZend Framework 2%s'), '<span class="zf-green">', '</span>') ?></h1>
    <p><?php echo sprintf($this->translate('Congratulations! You have successfully installed the %sZF2 Skeleton Application%s. You are currently running Zend Framework version %s. This skeleton can serve as a simple starting point for you to begin building your application on ZF2.'), '<a href="https://github.com/zendframework/ZendSkeletonApplication" target="_blank">', '</a>', \Zend\Version\Version::VERSION) ?></p>
    <p><a class="btn btn-success btn-lg" href="https://github.com/zendframework/zf2" target="_blank"><?php echo $this->translate('Fork Zend Framework 2 on GitHub') ?> &raquo;</a></p>
</div>-->


<script type="text/javascript"> 
    var url_save = "<?php echo $this->url('save') ?>";
    
    $(document).ready(function(){

		$("#form_registro").validate({
			debug: true,
			rules: {
				nombre: "required",
				apellidos: "required",
				email: {
					required: true,
					email: true
				}
			},
			messages: {
				nombre: "",
				apellidos: "",
				email: ""
			}
		});    	

    });

</script>


<div class="row">
    <form class="form form-cusquena" method="POST" id="form_registro">
        <div class="form-group">
            <label for="nombre">Nombre</label>
            <input type="text" class="form-control" id="nombre" placeholder="ESCRIBE EL NOMBRE" name="nombre">
        </div>
        <div class="form-group">
            <label for="apellidos">Apellidos</label>
            <input type="text" class="form-control" id="apellidos" placeholder="ESCRIBE EL APELLIDO" name="apellidos">
        </div>
        <div class="form-group">
            <label for="email">Correo Electr&oacute;nico</label>
            <input type="text" class="form-control" id="email" placeholder="ESCRIBE EL CORREO ELECTR&Oacute;NICO" name="email">
        </div>
        <div class="form-group">
            <label for="fecha_nacimiento">Fecha de Nacimiento</label>
            <div class="row">
            	<div class="col-md-3">
				    <input type="text" class="form-control" id="form_day" name="form_day" maxlength="2" tabindex="4" value="DD" data-last-value="DD" data-reg="">
			    </div>
            	<div class="col-md-3">
				    <input type="text" class="form-control" id="form_month" name="form_month" maxlength="2" tabindex="5" value="MM" data-last-value="MM" data-reg="">
			    </div>
            	<div class="col-md-3">
				    <input type="text" class="form-control" id="form_year" name="form_year" maxlength="4" tabindex="6" value="AAAA" data-last-value="AAAA" data-reg="">
			    </div>
            </div>
            <input type="hidden" class="form-control" id="fecha_nacimiento" placeholder="Ingrese su Fecha de Nacimiento" name="fecha_nacimiento">
        </div>
        <div class="form-group">
            <label for="dni">DNI</label>
            <input type="text" class="form-control" id="dni" placeholder="ESCRIBE EL DNI" name="dni">
        </div>
        <div class="form-group">
            <label for="telefono">Tel&eacute;fono</label>
            <input type="text" class="form-control" id="telefono" placeholder="ESCRIBE EL N&Uacute;MERO DE TEL&Eacute;FONO" name="telefono">
        </div>
        <div class="form-group">
            <label for="codigo_premiacion">C&oacute;digo</label>
            <input type="text" class="form-control" id="codigo_premiacion" placeholder="ESCRIBE EL C&Oacute;DIGO" name="codigo_premiacion">
        </div>
        <div class="form-group">
            <label for="agencia">Ingresa la agencia BBVA CONTINENTAL m&aacute;s cerca </label>
            <input type="text" class="form-control" id="agencia" placeholder="ESCRIBA EL NOMBRE DE LA AGENCIA" name="agencia">
        </div>
<!--        
        <div class="form-group">
            <label for="direccion">Direcci&oacute;n</label>
            <input type="text" class="form-control" id="direccion" placeholder="Escriba su Direcci&oacute;n" name="direccion">
        </div>
-->
        <div class="form-group">
            <button id="enviar" type="button" class="btn btn-primary btn-saveuser">Guardar</button>
        </div>
    </form>
</div>

