<div class="row">
    <form class="form form-cusquena" method="POST" id="form_registro">
        <div class="form-group">
            <label for="nombre">Nombre</label>
            <input type="text" class="form-control" id="nombre" placeholder="ESCRIBE EL NOMBRE" name="nombre" tabindex="1">
        </div>
        <div class="form-group">
            <label for="apellidos">Apellidos</label>
            <input type="text" class="form-control" id="apellidos" placeholder="ESCRIBE EL APELLIDO" name="apellidos" tabindex="2">
        </div>
        <div class="form-group">
            <label for="email">Correo Electr&oacute;nico</label>
            <input type="text" class="form-control" id="email" placeholder="ESCRIBE EL CORREO ELECTR&Oacute;NICO" name="email" tabindex="3">
        </div>
        <div class="form-group">
            <label for="fecha_nacimiento">Fecha de Nacimiento</label>
            <div class="row">
            	<div class="col-xs-3">
				    <input type="text" class="form-control" id="form_day" name="form_day" maxlength="2" tabindex="4" placeholder="DD">
			    </div>
            	<div class="col-xs-3">
				    <input type="text" class="form-control" id="form_month" name="form_month" maxlength="2" tabindex="5" placeholder="MM">
			    </div>
            	<div class="col-xs-4">
				    <input type="text" class="form-control" id="form_year" name="form_year" maxlength="4" tabindex="6" placeholder="AAAA">
			    </div>
            </div>
            <input type="text" class="form-control" id="fecha_nacimiento" name="fecha_nacimiento" style="display: none !important;">
        </div>
        <div class="form-group">
            <label for="dni">DNI</label>
            <input type="text" class="form-control" id="dni" placeholder="ESCRIBE EL DNI" name="dni" tabindex="7" maxlength="8">
        </div>
        <div class="form-group">
            <label for="telefono">Tel&eacute;fono</label>
            <input type="text" class="form-control" id="telefono" placeholder="ESCRIBE EL N&Uacute;MERO DE TEL&Eacute;FONO" name="telefono" tabindex="8" maxlength="9">
        </div>
        <div class="form-group">
            <label for="codigo_premiacion">C&oacute;digo</label>
            <input type="text" class="form-control" id="codigo_premiacion" placeholder="ESCRIBE EL C&Oacute;DIGO" name="codigo_premiacion" maxlength="8" tabindex="9">
        </div>
        <div class="form-group">
            <label for="agencia" style="text-transform: none;">Ingresa la agencia BBVA CONTINENTAL m&aacute;s cerca </label>
            <input type="text" class="form-control" id="agencia" placeholder="ESCRIBA EL NOMBRE DE LA AGENCIA" name="agencia" tabindex="10">
        </div>
<!--        
        <div class="form-group">
            <label for="direccion">Direcci&oacute;n</label>
            <input type="text" class="form-control" id="direccion" placeholder="Escriba su Direcci&oacute;n" name="direccion">
        </div>
-->
        <div class="form-group">
            <button id="enviar" type="submit" class="btn btn-primary btn-saveuser">Guardar</button>
        </div>
    </form>

	<script type="text/javascript"> 
	    var url_save = "<?php echo $this->url('save') ?>";
	    
	    $(function(){
	    	
	    	$('#form_registro input').placeholder();
	    	
			$("#form_registro").validate({
				debug: true,
				ignore: '',
				onkeyup: function(element, event){
					if ( event.which === 9 && this.elementValue(element)  === "") {
			            return;
			        } else {
			            this.element(element);
			        }
				},
				errorElement: "div",
				errorPlacement: function(error, element) {
					error.insertAfter(element);
				},
				submitHandler: function(form) {
					
					var o_form = new Object();
					o_form.nombre = $('#nombre').val();
					o_form.apellidos = $('#apellidos').val();
					o_form.email = $('#email').val();
					o_form.fecha_nacimiento = $('#fecha_nacimiento').val();
					o_form.dni = $('#dni').val();
					o_form.telefono = $('#telefono').val();
					o_form.codigo_premiacion = $('#codigo_premiacion').val();
					o_form.agencia = $('#agencia').val();
					
					$.ajax({
		                url:url_save
		                ,data:{form:o_form}
		                ,type:'POST'
		                ,datatype:'json'
		                ,async:true
		                ,success:function(response){
		                    var rpta = JSON.parse(response);
		                        if(rpta.value == 1){
		                        	console.log('OK');
		                        }
		                        if(rpta.value==0){console.log('invalidos');}
		                        if(rpta.value==2){console.log('invalidos');}
		                  
		                }
		            });
				},
				rules: {
					nombre: {
						required: true
					},
					apellidos: {
						required: true
					},
					email: {
						required: true,
						email: true
					},
					form_day: {
						required: true,
						digits: true
					},
					form_month: {
						required: true,
						digits: true
					},
					form_year: {
						required: true,
						digits: true
					},
					fecha_nacimiento: {
						required: true,
						date: true
					},
					dni: {
						required: true,
						digits: true
					},
					telefono: {
						required: true,
						digits: true
					},
					codigo_premiacion: {
						required: true,
					},
					agencia: {
						required: true
					}
				},
				messages: {
					nombre: 'Llene correctamente este campo',
					apellidos: 'Llene correctamente este campo',
					email: {
						required: 'Llene correctamente este campo',
						email: 'Llene correctamente este campo'
					},
					form_day: '',
					form_month: '',
					form_year: '',
					fecha_nacimiento: {
						required: 'Llene correctamente este campo',
						date: 'Llene correctamente este campo'
					},
					dni: {
						required: 'Llene correctamente este campo',
						digits: 'Llene correctamente este campo'
					},
					telefono: {
						required: 'Llene correctamente este campo',
						digits: 'Llene correctamente este campo'
					},
					codigo_premiacion: {
						required: 'Llene correctamente este campo'
					},
					agencia: {
						required: 'Llene correctamente este campo'
					}

					
				}
			});
	

			$('#nombre, #apellidos').filter_input({regex:'[a-zA-Z\u00C1\u00E1\u00C9\u00E9\u00CD\u00ED\u00D3\u00F3\u00DA\u00FA\u00D1\u00F1 ]'}); 
			$('#dni, #telefono').filter_input({regex:'[0-9]'})
			
			// filter & build date
			$('#form_day, #form_month, #form_year').on('keyup', function(evt){
				this.value = this.value.replace(/[^0-9]/g, '');
				if(this.value.length == parseInt(this.attributes['maxlength'].value))
				{
					$('input#fecha_nacimiento').val( [ $('input#form_year').val(), $('input#form_month').val(), $('input#form_day').val() ].join('/') );
				}
			});

	    });
		
	</script>



</div>

