<!--<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Welcome to %sZend Framework 2%s'), '<span class="zf-green">', '</span>') ?></h1>
    <p><?php echo sprintf($this->translate('Congratulations! You have successfully installed the %sZF2 Skeleton Application%s. You are currently running Zend Framework version %s. This skeleton can serve as a simple starting point for you to begin building your application on ZF2.'), '<a href="https://github.com/zendframework/ZendSkeletonApplication" target="_blank">', '</a>', \Zend\Version\Version::VERSION) ?></p>
    <p><a class="btn btn-success btn-lg" href="https://github.com/zendframework/zf2" target="_blank"><?php echo $this->translate('Fork Zend Framework 2 on GitHub') ?> &raquo;</a></p>
</div>-->


<script type="text/javascript"> 
    var url_save = "<?php echo $this->url('save') ?>";
    
    $(document).ready(function(){
        $("#enviar").click(function(){
            var o_form = new Object();
            o_form.nombre = $("#nombre").val();
            o_form.apellidos = $("#apellidos").val();
            o_form.fecha_nacimiento = $("#fecha_nacimiento").val();
            o_form.dni = $("#dni").val();
            o_form.telefono = $("#telefono").val();
            o_form.codigo_premiacion = $("#codigo_premiacion").val();
            o_form.email = $("#email").val();
            o_form.agencia = $("#agencia").val();
            o_form.direccion = $("#direccion").val();
            $.ajax({
                url:'/application/index/save'
                ,data:{form:o_form}
                ,type:'POST'
                ,datatype:'json'
                ,async:true
                ,success:function(response){
                  ;
                }
            });  
        });
    });

</script>


<div class="row">
    <form class="form form-cusquena" method="POST" id="form_registro">
        <div class="form-group">
            <label for="nombre">Nombre(s)</label>
            <input type="text" class="form-control" id="nombre" placeholder="Nombre" name="nombre">
        </div>
        <div class="form-group">
            <label for="apellidos">Apellidos</label>
            <input type="text" class="form-control" id="apellidos" placeholder="Apellidos" name="apellidos">
        </div>
        <div class="form-group">
            <label for="fecha_nacimiento">Fecha de Nacimiento</label>
            <input type="text" class="form-control" id="fecha_nacimiento" placeholder="Ingrese su Fecha de Nacimiento" name="fecha_nacimiento">
        </div>
        <div class="form-group">
            <label for="dni">DNI</label>
            <input type="text" class="form-control" id="dni" placeholder="Ingrese su DNI" name="dni">
        </div>
        <div class="form-group">
            <label for="telefono">Tel&eacute;fono</label>
            <input type="text" class="form-control" id="telefono" placeholder="Ingrese su telefono" name="telefono">
        </div>
        <div class="form-group">
            <label for="codigo_premiacion">C&oacute;digo de Premiaci&oacute;n</label>
            <input type="text" class="form-control" id="codigo_premiacion" placeholder="Ingrese su C&oacute;digo de Premiaci&oacute;n" name="codigo_premiacion">
        </div>
        <div class="form-group">
            <label for="email">Correo Electr&oacute;nico</label>
            <input type="text" class="form-control" id="email" placeholder="Ingrese su Correo Electr&oacute;nico" name="email">
        </div>
        <div class="form-group">
            <label for="agencia">Agencia BBVA</label>
            <input type="text" class="form-control" id="agencia" placeholder="Escriba el nombre de la Agencia" name="agencia">
        </div>
        <div class="form-group">
            <label for="direccion">Direccion</label>
            <input type="text" class="form-control" id="direccion" placeholder="Escriba su Direccion" name="direccion">
        </div>
        <div class="form-group">
            <button id="enviar" type="button" class="btn btn-primary btn-saveuser">Guardar</button>
        </div>
    </form>
</div>

