<div class="row">
	<form class="form-login form-cusquena" method="POST" id="form_login"> 
	    <div class="form-group">
	        <label for="user">Usuario</label>
	        <input type="text" class="form-control" id="user" name="user">
	    </div>
	    <div class="form-group">
	        <label for="password">Contrase&ntilde;a</label>
	        <input type="password" class="form-control" id="password" name="password">
	    </div>
	    <center>
	        <button id="loggin" class="btn btn-large btn-primary btn-sign-in" type="submit">Entrar</button>
	    </center>
	</form>
</div>


<script type="text/javascript"> 
    var url_save = "<?php echo $this->url('save') ?>";
    
    $(document).ready(function(){
    	
    	
			$("#form_login").validate({
				debug: false,
				ignore: '',
				onkeyup: function(element, event){
					if ( event.which === 9 && this.elementValue(element)  === "") {
			            return;
			        } else {
			            this.element(element);
			        }
				},
				errorElement: "div",
				errorPlacement: function(error, element) {
					error.insertAfter(element);
				},
				submitHandler: function(form) {

		            var o_form = new Object();
		            o_form.user = $("#user").val();
		            o_form.password = $("#password").val();
		            $.ajax({
		                url:'/application/index/login'
		                ,data:{form:o_form}
		                ,type:'POST'
		                ,datatype:'json'
		                ,async:true
		                ,success:function(response){
		                    var rpta = JSON.parse(response);
		                        if(rpta.value == 1){
		                             $(location).attr('href',"<?php echo $this->url('form') ?>");                 
		                        }
		                        if(rpta.value==0){console.log('invalidos');}
		                        if(rpta.value==2){console.log('invalidos');}
		                  
		                }
		            });  
				},
				rules: {
					user: {
						required: true
					},
					password: {
						required: true
					}
				},
				messages: {
					user: 'Llene correctamente este campo',
					password: 'Llene correctamente este campo'
				}
			});
    	
    });

</script>
